### ISSUE TITLE
send: TypeError

### ISSUE THREAD

**Issue by swat69** [vergecurrency/electrum#15]
During the send procedere, I'm getting this error, but the transaction is broadcasted.
(Win10, latest v4.0.0-beta3:)

![image](https://user-images.githubusercontent.com/28594828/75195206-cd856a00-5759-11ea-9351-6d6139ab7ed0.png)
After pressing Send:

![image](https://user-images.githubusercontent.com/28594828/75195150-b0509b80-5759-11ea-95a7-36c66db23991.png)

**Comment by justinvforvendetta** [comment]
looks like it could be related to the server instead of the client...
https://github.com/spesmilo/electrum/issues/5106

**Comment by justinvforvendetta** [comment]
which electrum server are you running @swat69

**Comment by swat69** [comment]
https://github.com/vergecurrency/electrumx/commit/4c1ed9667ab80bb15717624dc1203a651f80db17

**Comment by swat69** [comment]
workaround:
#19 
I think Client is to old, to many commits behind spesmilo/electrum

**Comment by swat69** [comment]
revoke workaround #19 , because it broke Pending/Unpaid/Paid functionality
fixed with #22
