### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Umaroth** [vergecurrency/electrum#25]
I've been trying to get this to connect to a server for 3 hours. Nothing is working and there's nothing resembling support anywhere I can find and every single article I can find about this issue doesn't work.

Please help.

How do you get this to connect to a server?

I'm using Release v4.0.0-beta3 because the newest version didn't have any Windows binaries and I can't compile them

**Comment by Grigory442** [comment]
i have the same problem, tried all possible verge servers. haven't found a solution?

**Comment by swat69** [comment]
meanwhile only Tor servers are available:
start Tor browser, enable proxy in the wallet (socks5, localhost, 9150) with server= 4eif6aox6iwhmqff.onion
v4.0.1 is using the proxy by default

**Comment by Grigory442** [comment]
Thank you so much!

notifications@github.com  <notifications@github.com>:
