### ISSUE TITLE
Unconfirmed Transaction stuck in Mem Pool

### ISSUE THREAD

**Issue by altagir** [vergecurrency/electrum#29]
Wallet initially created on linux / electrum-xvg 
Finally found a working / synching wallet (windows / electrum)

I got an error, which I did not copy  (about some quotes required on a field) but the transaction has been created and just sit there unconfirmed
https://verge-blockchain.info/tx/3af9bf6f5b4208c1a8be413b5413ff35b8c0ead242ea13ecde69fe4218dba576

It also appears as the only one pending in the queue, with other transactions passing through

I cannot seem to cancel it with electrum

Any help appreciated.

**Comment by swat69** [comment]
your tx has a time in the future:  (in 1h and 20min)
Time | Epoch 28 Feb 2021 - 02:15 AM | 1614474903

I changed by windows time to March 1 and made a tx with the same result:  -pending-
[https://verge-blockchain.info/tx/f2f88baae30a98b95267c3ad788ccd33e439c18e302b0e81f68a27c626e37587](url)

**Comment by swat69** [comment]
your tx has a time in the future: (in 1h and 15min)
Time | Epoch 28 Feb 2021 - 02:15 AM | 1614474903

I changed my windows time to March 1 and made a tx with same result: --pending--
[https://verge-blockchain.info/tx/f2f88baae30a98b95267c3ad788ccd33e439c18e302b0e81f68a27c626e37587](url)

**Comment by altagir** [comment]
Thanks a lot for your reply :)
Uhm I am linux user so my BIOS clock is set to UTC
I only booted windows to get a working wallet, and usually Windows time is off.
I haven't noticed it was not synchronized
Will wait for time to pass

Quick question, why was the transaction so big ? it includes all mining history. Made the transfert quite costly (2 xvg)

**Comment by altagir** [comment]
Thanks, it was indeed the issue
Thanks for your time @swat69 :)
