### ISSUE TITLE
electrum not sync

### ISSUE THREAD

**Issue by thiagomen001** [vergecurrency/electrum#32]
Hi,

I just imported my private key on electrum with a history of transactions of several years but I have a problem all the transactions are displayed not verified while they are on the blockchain.

How can I do to sync well having only one server in onion?

**Comment by swat69** [comment]
The wallet will download some data (approx 30min), after this your transactions will become verified.

**Comment by thiagomen001** [comment]
> The wallet will download some data (approx 30min), after this your transactions will become verified.

Thanks for your answer @swat69 
A confirmation in 3 hours.
I have more than a dozen, it is not embarrassing but for the estethics it will take me 1 month to sync everything. If someone has already had this problem and has a faster solution, tell me.

**Comment by swat69** [comment]
I increased the sessions limits on the server, maybe you see a difference

**Comment by thiagomen001** [comment]
> I increased the sessions limits on the server, maybe you see a difference

Okay, I'll try to get it synchronized for a while.

I take advantage of my topic to know if it is possible to create a seed from electrum or septem to use also myvergies?
@swat69
