### ISSUE TITLE
can not connect

### ISSUE THREAD

**Issue by jazzvh** [vergecurrency/electrum#35]
i can not connect to my electrum verge wallet. i dont understand why i can not post about it? it is a bug and i does not work. and this is the site im send to for help when i press help from my wallet and i cant find any help. how am i supost to find help if i cant ask for it?

**Comment by jazzvh** [comment]
i am conntected to tor browser. i have the 4.0,3 version. i tried sereval diffrent servers. i dont know where i can find more servers t try. what els is there to do?

**Comment by swat69** [comment]
there is only one valid server at the moment
maybe you harmed your proxy configuration
In any case is this a local issue, the server is online with several wallets connected

you can try:
1 stop wallet
2 delete config file ...\Electrum_XVG\config
3 start (this will create a new configuration with the default server)
4 stop
5 start
