### ISSUE TITLE
"Electrum" is not synced with  "Block Explorer"

### ISSUE THREAD

**Issue by Babak5153** [vergecurrency/electrum#37]
Hi there,
 "block explorer" shows confirmation and amount of  received XVG correctly ,but it's not synced on "Electrum" , the electrum is empty! 
 help please.

**Comment by Babak5153** [comment]
above issue is on version 4.0.3 (network is not connected)! on version 4.1.5 connection to server is OK but wallets are different

**Comment by swat69** [comment]
4.0.3 is the latest version, you have to start the 'Tor Browser' to get a connection. 4.1.5 is not VERGE electrum !

**Comment by Babak5153** [comment]
Thanks a lot Swat. It is working now.
