### ISSUE TITLE
Electrum verge 4.0.4 servers issue

### ISSUE THREAD

**Issue by Robin383838** [vergecurrency/electrum#40]
Dear all,

I really could use help here. I am trying to send some of my xvg balance, but the wallet apears to be offline!

The wallet is secured by trezor so i cannot export my private keys. Can someone please help by presenting new servers that will connect my wallet? The red dot is saying there is no connection.

Any help would be much appriciated.

Thank you so much in advance,

**Comment by Kellytimmins** [comment]
Hello @Robin383838 
It sounds like your wallet is having trouble connecting to the network. I'll have to refer you to the official support live chat with the ticket ID ELE07638
Please see the link below to our dedicated support line:
[Electrum Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by swat69** [comment]
SCAM. Don't click  the link.
Is your Tor Browser connected?
Please try to add server  "electrumx-verge.cloud"   port 50002

**Comment by Robin383838** [comment]
> SCAM. Don't click the link. Is your Tor Browser connected? Please try to add server "electrumx-verge.cloud" port 50002

Hi Swat, Thank you for your message. And thank you for the warning!

I am indeed connected to TOR
I just added your suggested server, unfortunatly still a red dot. I have PROXY on 127.0.0.1 / 9150. Is that correct?

**Comment by swat69** [comment]
there is no reason to edit the config, this is the default:
![image](https://github.com/user-attachments/assets/3cea3b5e-4483-4102-9768-f9202f42e204)

**Comment by Robin383838** [comment]
> there is no reason to edit the config, this is the default: ![image](https://private-user-images.githubusercontent.com/28594828/392856993-3cea3b5e-4483-4102-9768-f9202f42e204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDk0MDksIm5iZiI6MTczMzQwOTEwOSwicGF0aCI6Ii8yODU5NDgyOC8zOTI4NTY5OTMtM2NlYTNiNWUtNDQ4My00MTAyLTk3NjgtZjkyMDJmNDJlMjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0MzE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNWIzOWIwMTZmNDVlOTk0OTRiYWMyZTMwNWZiMWVhMTVlNjNiNDg1ZDBmZWI2MWU2ZTU1MTViY2FkZWQxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nmaFDg-9bNELYTZH0CaD31d0eIfGDXqyHv-4n89inq4)

Hi Swat, the dot has turned blue! Your are a great person to help and warn a stranger and prompt responses, much appriciated. Please share your receiving xvg address so i can send you some xvg to buy you a coffee/beer. :)

**Comment by swat69** [comment]
DNafruJXi5HWSTb2diapqDtGowjPaFq2Pg
:-)
Thanks Robin
